spring:
  application:
    name: post-service
  data:
    mongodb:
      database: test
      port: 27017
      host: travel-diary-mongo
    redis:
      host: travel-diary-redis
      port: 6379
  rabbitmq:
    host: travel-diary-rabbitmq
    port: 5672
    username: admin
    password: admin
rabbit:
  queue-name: travel-diary-exchange-rate

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://travel-diary-eureka:5776/eureka
logging:
  level:
    org:
      springframework:
        security: DEBUG
