server:
  port: 7080
spring:
  application:
    name: exchange-rate-service
  rabbitmq:
    host: travel-diary-rabbitmq
    port: 5672
    username: admin
    password: admin
rabbit:
  queue-name: travel-diary-exchange-rate
  exchange-name: travel-diary-exchange
  routing-key: some-secret-key
external:
  exchange-rate:
    url: http://www.cbr.ru/scripts/XML_daily.asp
scheduler:
  cron-expression: 0 * * * * *

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://travel-diary-eureka:5776/eureka
logging:
  level:
    org.springframework.security: DEBUG
    com.krokodillLl.traveldiary.exchangerate.external: DEBUG
